### ISSUE TITLE
Insert new camera Poses

### ISSUE THREAD

**Issue by sharish33** [cmitash/physics-scene-rendering-vision#8]
Hello, 

We find the github page so helpful to generate the synthetic dataset using blender. we are trying to generate more dataset by increasing the number of camera poses.In Config.yml, please can you let know how to insert new pose for camera poses.(I mean procedure to get the values for the new pose list[pos_x, pos_y, pos_z, quat_w, quat_x, quat_y, quat_z]). Then we will work on algorithm to generate the new camera pose instead of hard coding values. Your quick help would be great and more helpful.

Best Regards,
Hareesh

**Comment by cmitash** [comment]
Hi Hareesh,
There could be different ways to generate camera poses depending on the application. One of the common techniques for generating camera poses for training data generation is to sample it from a sphere centered at the object/specific part of the scene. You can refer to the following code for that purpose:
https://github.com/thodan/sixd_toolkit/blob/master/pysixd/view_sampler.py

Best,
Chaitanya

**Comment by sharish33** [comment]
Hi Chaitanya,

Thank you very much for your reply. I will try it out with this approach.

I have also seen in your video and webpage that you have generated depth image but I could not find any procedure in your pages to generate the depth image. Please could you let know which procedure you used to generate the depth, segmentation image dataset using blender.

Best regards,
Hareesh

**Comment by sharish33** [comment]
Thank you for your help.Issue is resolved
